/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enkripsi.dekripsi;


import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author GiePie
 */
public class endecrypt extends javax.swing.JFrame {

    /**
     * Creates new form endecrypt
     */
    public endecrypt() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlaintext = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChipertext = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnEnc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDec = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPER ENKRIPSI - GIVI OFGIVIA_TIF2018131028");
        setFont(new java.awt.Font("Susah Ngesubs SemiBold", 2, 10)); // NOI18N
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/yericomordor_32.png")).getImage());
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setToolTipText("Secure your message. Made with love by GiePie");
        jPanel1.setPreferredSize(new java.awt.Dimension(775, 650));

        jScrollPane1.setToolTipText("Pesan asli");

        txtPlaintext.setColumns(20);
        txtPlaintext.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtPlaintext.setRows(5);
        txtPlaintext.setToolTipText("Kolom Teks Polos");
        txtPlaintext.setAlignmentX(2.0F);
        txtPlaintext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPlaintext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPlaintext.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jScrollPane1.setViewportView(txtPlaintext);

        jScrollPane2.setToolTipText("Pesan yang telah di-enkrip");

        txtChipertext.setColumns(20);
        txtChipertext.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtChipertext.setLineWrap(true);
        txtChipertext.setRows(5);
        txtChipertext.setToolTipText("Kolom Teks Terenkripsi");
        jScrollPane2.setViewportView(txtChipertext);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        jLabel4.setToolTipText("(String) Berisi sandi yang akan dimasukkan ke Plain Text");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 70, 70, -1));

        txtKey.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtKey.setToolTipText("Pergeseran alfabet (dalam angka)");
        jPanel5.add(txtKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 234, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnc.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 12)); // NOI18N
        btnEnc.setText("Encrypt");
        btnEnc.setToolTipText("Lakukan Enkripsi");
        btnEnc.setMargin(new java.awt.Insets(4, 16, 4, 16));
        btnEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncActionPerformed(evt);
            }
        });
        jPanel6.add(btnEnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/icons8_encrypt_32.png"))); // NOI18N
        jLabel5.setToolTipText("Enkrip | Dekrip");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setIconTextGap(1);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, 60));

        btnDec.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 12)); // NOI18N
        btnDec.setText("Decrypt");
        btnDec.setToolTipText("Lakukan Dekripsi");
        btnDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecActionPerformed(evt);
            }
        });
        jPanel6.add(btnDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, -1));

        jButton1.setText(" ");
        jButton1.setToolTipText("Kosongkan Plain Text");
        jButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 12));

        jButton2.setText(" ");
        jButton2.setToolTipText("Kosongkan Encrypted Text");
        jButton2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 12));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 230, 80));

        btnExit.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 12)); // NOI18N
        btnExit.setText("Clear");
        btnExit.setToolTipText("Kosongkan seluruh input");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 234, -1));

        txtPass.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtPass.setText(" ");
        txtPass.setToolTipText("Kata Sandi ");
        jPanel5.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 234, -1));

        jLabel6.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cipher Key");
        jLabel6.setToolTipText("(int) Berisi jumlah pergeseran alfabet dari Plain Text");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("irohamaru mikami Regular", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("https://github.com/giviofg/superEnkripsi_java");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 12)); // NOI18N
        jLabel2.setText("Plain Text");
        jLabel2.setToolTipText("Berisi teks yang akan dienkripsi atau telah didekrip");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUPER ENCRYPTION");
        jLabel1.setToolTipText("Made with love by GiePie");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 12)); // NOI18N
        jLabel3.setText("Encrypted Text");
        jLabel3.setToolTipText("Berisi teks yang akan didekripsi atau telah dienkrip");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/yericomordor_64.png"))); // NOI18N
        jLabel7.setText(" ");
        jLabel7.setToolTipText("HOBI MGODONF");
        jLabel7.setMaximumSize(new java.awt.Dimension(72, 72));
        jLabel7.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 64, 64));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncActionPerformed
        // TODO add your handling code here:
//        String key = txtKey.getText();    jangan pakai ini gip
//        String isitext = (key.length())+key+txtPlaintext.getText();
//        String out = "";
//        for (int i = 0; i < isitext.length(); i++){
//            int index = isitext.charAt(i);
//            char s    = (char)(index+1);
//            out       = out + String.valueOf(s);
//        }
//        txtChipertext.setText(out);
//        txtPlaintext.setText("");
//        txtKey.setText("");

        if(txtKey.getText().equals("")||!(Pattern.matches("[0-9]+$", txtKey.getText()))){
//            JOptionPane.showMessageDialog(null, "CIPHER KEY NUMBERS ONLY!\nPlease check your inputs.");
            JOptionPane.showMessageDialog(null, "CIPHER KEYS ARE NUMBERS ONLY!\nPlease check your inputs.", "W A R N I N G", HEIGHT);
        }

        //ALTERNATIVE
        String txtplain = txtPlaintext.getText();
        String txtpass = txtPass.getText();
        String txtkey = txtplain+" "+txtpass;
        String txtencrypted="";
        Integer keyLength = Integer.valueOf(txtKey.getText());
        for(int i=0;i<txtkey.length();i++)
        {
            //stores ascii value of character in the string at index 'i'
            int bedahKey=txtkey.charAt(i);
            //encryption logic for uppercase letters
            if(Character.isUpperCase(bedahKey))
            {
                bedahKey=bedahKey+(keyLength%26);
                //if bedahKey value exceeds the ascii value of 'Z' reduce it by subtracting 26(no.of alphabets) to keep in boundaries of ascii values of 'A' and 'Z'
                if(bedahKey>'Z')
                    bedahKey=bedahKey-26;
            }
            //encryption logic for lowercase letters
            else if(Character.isLowerCase(bedahKey))
            {
                bedahKey=bedahKey+(keyLength%26);
                //if bedahKey value exceeds the ascii value of 'z' reduce it by subtracting 26(no.of alphabets) to keep in boundaries of ascii values of 'a' and 'z'
                if(bedahKey>'z')
                    bedahKey=bedahKey-26;
            }
            //concatinate the encrypted characters/strings
            txtencrypted=txtencrypted+(char) bedahKey;
            //txtChipertext.setText(txtencrypted);
        }
                
        String transposedCipher = LakukanTranspos_dari(txtencrypted);
        String txtTransposedCipher = String.valueOf(transposedCipher);
        txtChipertext.setText(txtTransposedCipher);
        txtPlaintext.setText("");
//        String pass = txtPass.getText();
        
        //HILL CIPHER DI SINI ternyata tak work awkoawkoakokaw
//        String hc = this.HillCipher(cpt, pass);
//        String hcc = String.valueOf(hc);
//        txtChipertext.setText(hcc);
                
//        String kalimat = encrypted;       ini pun tak work 
//        String[] kata  = kalimat.split(" ");
//        for(int x = 0; x < kata.length; x++){
//            String cipertrans = transpose(kata[x]);
//            String cpt = String.valueOf(cipertrans);
//            txtChipertext.setText(cpt);
//        }
//        String[] word = null;
//        String kata;
//        while((kata = encrypted) != null){
//            word = kata.split(" ");
//        }
    }//GEN-LAST:event_btnEncActionPerformed

    private void btnDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecActionPerformed
        // TODO add your handling code here:
//        String it  = txtChipertext.getText();
//        char k = (char)(it.charAt(0));
//        String key = "";
//        String out = "";
//        int jumkey = Integer.parseInt(String.valueOf(k))-1;
//        
//        for (int i = 1; i <= jumkey; i++){
//            int index = it.charAt(i);
//            char s = (char)(index-1);
//            key    = key + String.valueOf(s);
//        }
//        
//        if (key.equals(txtKey.getText())){
//            for (int i = (jumkey+1); i < it.length(); i++){
//                int index = it.charAt(i);
//                char s =(char)(index-1);
//                out    = out + String.valueOf(s);
//            }
//            txtPlaintext.setText(out);
//        } else {
//            JOptionPane.showMessageDialog(null, "Key tidak cocok!\nSilahkan cek kembali");
//        }

        if(txtKey.getText().equals("")||!(Pattern.matches("[0-9]+$", txtKey.getText()))){
//            JOptionPane.showMessageDialog(null, "CIPHER KEY NUMBERS ONLY!\nPlease check your inputs.");
            JOptionPane.showMessageDialog(null, "CIPHER KEYS ARE NUMBERS ONLY!\nPlease check your inputs.", "W A R N I N G", HEIGHT);
        }
        
        //ALTERNATIVE
        String txtcipher = txtChipertext.getText();
        String txtpass = txtPass.getText();
        Integer panjangKey = Integer.valueOf(txtKey.getText());
        String txtdecrypted="";
        String untransposedCipher = MentransposKembali_dari(txtcipher);
        String txtUntransposedCipher = String.valueOf(untransposedCipher);
        
            for(int i=0;i<txtUntransposedCipher.length();i++)
        {
            //stores ascii value of character in the string at index 'i'
            int bedahTeksCipher=txtUntransposedCipher.charAt(i);
            //decryption logic for uppercase letters
            if(Character.isUpperCase(bedahTeksCipher))
            {
                bedahTeksCipher=bedahTeksCipher-(panjangKey%26);
                //if bedahTeksCipher value deceed the ascii value of 'A' increase it by adding 26(no.of alphabets) to keep in boundaries of ascii values of 'A' and 'Z'
                if(bedahTeksCipher<'A')
                    bedahTeksCipher=bedahTeksCipher+26;
            }
            //decryption logic for uppercase letters
            else if(Character.isLowerCase(bedahTeksCipher))
            {
                bedahTeksCipher=bedahTeksCipher-(panjangKey%26);
                //if bedahTeksCipher value deceed the ascii value of 'A' increase it by adding 26(no.of alphabets) to keep in boundaries of ascii values of 'A' and 'Z'
                if(bedahTeksCipher<'a')
                    bedahTeksCipher=bedahTeksCipher+26;
            }
            //concatinate the decrypted characters/strings
            txtdecrypted=txtdecrypted+(char) bedahTeksCipher;
//            txtPlaintext.setText(txtdecrypted);
//            String temp = CharMatcher.anyOf(txtpass).removeFrom(txtdecrypted);

//            char[] temp = txtpass.toCharArray();
//            String rmv = remove3(txtdecrypted, temp);
//            txtPlaintext.setText(rmv);

            String plaintext = buangPass(txtdecrypted,txtpass);            
            txtPlaintext.setText(plaintext);
            txtChipertext.setText("");
        }
    }//GEN-LAST:event_btnDecActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        txtPlaintext.setText("");
        txtChipertext.setText("");
        txtKey.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtPlaintext.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtChipertext.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
//        Icon img = new ImageIcon("/enkripsi/dekripsi/yericomordor_32.png");
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/icons8_encrypts_32.png")));        
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/icons8_encrypt_32.png")));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        String cipherKey = "<html><u>Cipher Key</u></html>";
        jLabel6.setText(cipherKey);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setText("Cipher Key");
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        String pt = "<html><u>Plain Text</u></html>";
        jLabel2.setText(pt);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setText("Plain Text");
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(72, 72));
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 72, 72));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/yericomordor_72.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 18));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/yericomordor_64.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
         jLabel1.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(72, 72));
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 72, 72));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/yericomordor_72.png")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel1.setFont(new java.awt.Font("Susah Ngesubs SemiBold", 0, 18));
        jLabel7.setPreferredSize(new java.awt.Dimension(64, 64));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enkripsi/dekripsi/yericomordor_64.png")));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new endecrypt().setVisible(true);
        });
    }
    
    public static String LakukanTranspos_dari(String transpos)
    {
        /* Code ini didapat dari
           https://stackoverflow.com/a/2626718 */
        
        int length = transpos.length();
        int end = length - 1;

        StringBuilder t = new StringBuilder();
        for (int i = 0; i < length / 2; i++)
        {
            t.append(transpos.charAt(i));
            t.append(transpos.charAt(end));
            end--;
        }

        // JIKA Length of String is odd
        if (length % 2 == 1)
        {
            // add character in middle of String to the end of the new String
            t.append(transpos.charAt(length / 2));
        }
        return t.toString();
    }

    public static String MentransposKembali_dari(String untranspos)
    {
        /* Code ini didapat dari
           https://stackoverflow.com/a/2626718 */
        
        int length = untranspos.length();
        StringBuilder t = new StringBuilder();

        if (length % 2 == 1)
        {
            for (int i = 0; i < length; i += 2)
            {
                t.append(untranspos.charAt(i));
            }

            for (int i = length - 2; i > 0; i -= 2)
            {
                t.append(untranspos.charAt(i));
            }
        }
        else if (length % 2 == 0)
        {
            for (int i = 0; i < length - 1; i += 2)
            {
                t.append(untranspos.charAt(i));
            }

            for (int i = length - 1; i > 0; i -= 2)
            {
                t.append(untranspos.charAt(i));
            }
        }
        return t.toString();
    }
    
//    public static String transpose(String str) {
//
//        if (str == null || str.length() == 1 || str.length() == 2) {
//            return str;
//        } else {
//            return str.substring(0, 1) + str.substring(str.length() -1, str.length()) + transpose(str.substring(1, str.length() -1) );
//        }
//}
//
//    public static String untranspose(String str) {
//            if (str == null || str.length() == 1 ||str.length() == 2) {
//                return str;
//            } else {
//                return  str.substring(0, 1) + untranspose(str.substring(2, str.length())) + str.substring(1, 2);
//            }
//    }
    
//    public static String transpose(String s) {
//        StringBuilder sb = new StringBuilder();
//        sb.setLength(s.length());
//        for (int i = 0, j = s.length() - 1, x = 0; i <= j; ) {
//            sb.setCharAt(x++, s.charAt(i++));
//            if (i > j) break;
//            sb.setCharAt(x++, s.charAt(j--));
//        }
//        return sb.toString();
//    }  
//
//    public static String untranspose(String s) {
//        StringBuilder sb = new StringBuilder();
//        sb.setLength(s.length());
//        for (int i = 0, j = s.length() - 1, x = 0; i <= j; ) {
//            sb.setCharAt(i++, s.charAt(x++));
//            if (i > j) break;
//            sb.setCharAt(j--, s.charAt(x++));
//        }
//        return sb.toString();
//    }
    
    // Following function generates the 
// key matrix for the key string 
//static void getKeyMatrix(String key, int keyMatrix[][]) 
//{ 
//    int k = 0; 
//    for (int i = 0; i < 3; i++)  
//    { 
//        for (int j = 0; j < 3; j++)  
//        { 
//            keyMatrix[i][j] = (key.charAt(k)) % 65; 
//            k++; 
//        } 
//    } 
//} 
//  
//// Following function encrypts the message 
//static void encrypt(int cipherMatrix[][], 
//            int keyMatrix[][],  
//            int messageVector[][]) 
//{ 
//    int x, i, j; 
//    for (i = 0; i < 3; i++)  
//    { 
//        for (j = 0; j < 1; j++) 
//        { 
//            cipherMatrix[i][j] = 0; 
//          
//            for (x = 0; x < 3; x++) 
//            { 
//                cipherMatrix[i][j] +=  
//                    keyMatrix[i][x] * messageVector[x][j]; 
//            } 
//          
//            cipherMatrix[i][j] = cipherMatrix[i][j] % 26; 
//        } 
//    } 
//} 
//  
//// Function to implement Hill Cipher 
//public static String HillCipher(String message, String key) 
//{ 
//    // Get key matrix from the key string 
//    int [][]keyMatrix = new int[3][3]; 
//    getKeyMatrix(key, keyMatrix); 
//  
//    int [][]messageVector = new int[3][1]; 
//  
//    // Generate vector for the message 
//    for (int i = 0; i < 3; i++) 
//        messageVector[i][0] = (message.charAt(i)) % 65; 
//  
//    int [][]cipherMatrix = new int[3][1]; 
//  
//    // Following function generates 
//    // the encrypted vector 
//    encrypt(cipherMatrix, keyMatrix, messageVector); 
//  
//    String CipherText=""; 
//  
//    // Generate the encrypted text from  
//    // the encrypted vector 
//    for (int i = 0; i < 3; i++) 
//        CipherText += (char)(cipherMatrix[i][0] + 65); 
//  
//    // Finally print the ciphertext 
//    //System.out.print(" Ciphertext:" + CipherText);
//    return CipherText;
//} 
   
//    public static String remove3(final String string, final char... chars) {
//        char[] arr = string.toCharArray();
//        int dst=0;
//        for (int src=0; src<arr.length; src++) {
//            boolean rm = false;
//            for (char c : chars) {
//                if (c == arr[src]) {
//                    rm = true;
//                }
//            }
//            if (!rm) {
//                arr[dst++] = arr[src];
//            }
//        }
//        return dst == string.length() ? string : new String(arr, 0, dst);
//    }
    
    public static String buangPass(String string, String word) 
    { 
        /* Code ini didapat dari 
           https://www.geeksforgeeks.org/remove-a-given-word-from-a-string/ */
        
        // Check if the word is present in string 
        // If found, remove it using removeAll() 
        if (string.contains(word)) { 
  
            // To cover the case 
            // if the word is at the 
            // beginning of the string 
            // or anywhere in the middle 
            String tempWord = word + " "; 
            string = string.replaceAll(tempWord, ""); 
  
            // To cover the edge case 
            // if the word is at the 
            // end of the string 
            tempWord = " " + word; 
            string = string.replaceAll(tempWord, ""); 
        } 
  
        // Return the resultant string 
        return string; 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDec;
    public javax.swing.JButton btnEnc;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtChipertext;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextArea txtPlaintext;
    // End of variables declaration//GEN-END:variables
}
